### PR TITLE
Add Salt2 Fits

### PR DESCRIPTION
**Pull request by djperrefort**
Major changes:
- Adds a the `objects/salt2/` for displaying a table of recent Salt2 fits
- Adds a Salt2 section to object summary pages. The section is only rendered for pages with available Salt2 data.
  -  The object summary section is rendered dynamically using the new `broker_web/static/js/value_added_sections/salt2.js` script.

Minor changes:
- Adds the `limit` argument when rendering json views to limit the total number of rteturned results
- Adds the `urlparams` template tag for appending arguments to URL's

### CODE REVIEW

**Comment by djperrefort** [comment]
@mwvgroup/broker Looking for a volunteer reviewer. Any takers?

**Comment by troyraen** [comment]
@cmazzdaher Is this something you have time to look at?

**Comment by cmazzdaher** [comment]
@troyraen @djperrefort  Sure, I'll try to take a look

**Comment by troyraen** [comment]
@cmazzdaher Thank you!

**Comment by cmazzdaher** [comment]
@djperrefort Okay, so I mostly looked over the changes to
- broker_web/static/js/value_added_sections/salt2.js
- broker_web/templates/objects/salt2_fits.html
- broker_web/templates/objects/objects_summary.html
with glances at changes to other files from individual commits, to make sense of things. I'm not super familiar with the syntax, but I didn't see anything that seemed obviously wrong/strange. I like that the buckets are specified in the settings.py file rather than explicitly defined in the js. Deciphering all the formatting details would be painstaking without viewing the updated website myself, so I can't say I looked at all those very carefully. I assume you did look at the results yourself, though, so I'm sure they're fine.

I didn't try to run this branch on my local machine, but if it's passing checks and you're asking to merge, then I'm assuming it works. Unless anyone has any other objections or wants to take a look, I think it's okay to merge.

**Comment by djperrefort** [comment]
Thanks @cmazzdaher, I'll merge this in then.

**Pull request merged**
