### PR TITLE
Fill out Getting Started documentation.

### PR DESCRIPTION
**Pull request by wmwv**
Include conceptual diagram of broker
List planned APIs including full streams and copy of PPDB.
Introduce Semantically compressed streams.

### CODE REVIEW

**Comment by wmwv** [comment]
Thanks for the Django notes.  How do I test that things are working?

**Comment by wmwv** [comment]
> How do I test that things are working?
OK, I understand that the first easy one is making sure the Travis CI build passed.
But I don't see how redoing the steps of the Travis CI build is quite the right thing to check on my local machine.

**Comment by djperrefort** [comment]
Travis tests the python logic, but won't catch HTML issues like the one above. To check that pages render correctly, I launch a local Django server and navigate to that page on my local machine. The steps for doing so are listed [here](https://broker-web.readthedocs.io/en/latest/configuration/installation.html)

**Comment by djperrefort** [comment]
@wmwv Can I merge this in?

**Pull request merged**
